2019-12-12 12:03:46.264 INFO [restartedMain]com.wl.foodspringboot.FoodSpringBootApplication.logStarting:50 -Starting FoodSpringBootApplication on DESKTOP-814O8JJ with PID 1184 (E:\Learn\IdeaProjects\FoodSpringBoot\target\classes started by WL in E:\Learn\IdeaProjects\FoodSpringBoot)
2019-12-12 12:03:46.291 INFO [restartedMain]com.wl.foodspringboot.FoodSpringBootApplication.logStartupProfileInfo:647 -No active profile set, falling back to default profiles: default
2019-12-12 12:03:46.433 INFO [restartedMain]o.s.b.devtools.env.DevToolsPropertyDefaultsPostProcessor.logTo:225 -Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
2019-12-12 12:03:46.434 INFO [restartedMain]o.s.b.devtools.env.DevToolsPropertyDefaultsPostProcessor.logTo:225 -For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
2019-12-12 12:03:48.525 INFO [restartedMain]o.s.d.repository.config.RepositoryConfigurationDelegate.multipleStoresDetected:244 -Multiple Spring Data modules found, entering strict repository configuration mode!
2019-12-12 12:03:48.533 INFO [restartedMain]o.s.d.repository.config.RepositoryConfigurationDelegate.registerRepositoriesIn:126 -Bootstrapping Spring Data repositories in DEFAULT mode.
2019-12-12 12:03:48.628 INFO [restartedMain]o.s.d.repository.config.RepositoryConfigurationDelegate.registerRepositoriesIn:182 -Finished Spring Data repository scanning in 32ms. Found 0 repository interfaces.
2019-12-12 12:03:49.311 INFO [restartedMain]o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.postProcessAfterInitialization:330 -Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$9c548c6f] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-12-12 12:03:50.290 INFO [restartedMain]o.s.boot.web.embedded.tomcat.TomcatWebServer.initialize:90 -Tomcat initialized with port(s): 8080 (http)
2019-12-12 12:03:50.324 INFO [restartedMain]org.apache.coyote.http11.Http11NioProtocol.log:173 -Initializing ProtocolHandler ["http-nio-8080"]
2019-12-12 12:03:50.350 INFO [restartedMain]org.apache.catalina.core.StandardService.log:173 -Starting service [Tomcat]
2019-12-12 12:03:50.351 INFO [restartedMain]org.apache.catalina.core.StandardEngine.log:173 -Starting Servlet engine: [Apache Tomcat/9.0.22]
2019-12-12 12:03:50.364 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -An older version [1.2.21] of the APR based Apache Tomcat Native library is installed, while Tomcat recommends a minimum version of [1.2.23]
2019-12-12 12:03:50.365 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -Loaded APR based Apache Tomcat Native library [1.2.21] using APR version [1.6.5].
2019-12-12 12:03:50.365 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
2019-12-12 12:03:50.365 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
2019-12-12 12:03:50.416 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -OpenSSL successfully initialized [OpenSSL 1.1.1a  20 Nov 2018]
2019-12-12 12:03:50.590 INFO [restartedMain]o.a.c.c.C.[Tomcat].[localhost].[/foodspringboot].log:173 -Initializing Spring embedded WebApplicationContext
2019-12-12 12:03:50.591 INFO [restartedMain]org.springframework.web.context.ContextLoader.prepareWebApplicationContext:284 -Root WebApplicationContext: initialization completed in 4157 ms
2019-12-12 12:03:51.646 INFO [restartedMain]org.messaginghub.pooled.jms.JmsPoolConnectionFactory.setConnectionFactory:198 -Provided ConnectionFactory implementation is JMS 2.0+ capable.
2019-12-12 12:03:52.941 INFO [restartedMain]o.s.scheduling.concurrent.ThreadPoolTaskExecutor.initialize:171 -Initializing ExecutorService 'applicationTaskExecutor'
2019-12-12 12:03:53.007 INFO [restartedMain]o.s.b.a.web.servlet.WelcomePageHandlerMapping.<init>:54 -Adding welcome page: class path resource [public/index.html]
2019-12-12 12:03:53.050 WARN [restartedMain]org.thymeleaf.templatemode.TemplateMode.parse:150 -[THYMELEAF][restartedMain] Template Mode 'HTML5' is deprecated. Using Template Mode 'HTML' instead.
2019-12-12 12:03:53.606 INFO [restartedMain]o.s.boot.devtools.autoconfigure.OptionalLiveReloadServer.startServer:57 -LiveReload server is running on port 35729
2019-12-12 12:03:54.355 INFO [restartedMain]org.apache.coyote.http11.Http11NioProtocol.log:173 -Starting ProtocolHandler ["http-nio-8080"]
2019-12-12 12:03:54.376 INFO [restartedMain]o.s.boot.web.embedded.tomcat.TomcatWebServer.start:202 -Tomcat started on port(s): 8080 (http) with context path '/foodspringboot'
2019-12-12 12:03:54.379 INFO [restartedMain]com.wl.foodspringboot.FoodSpringBootApplication.logStarted:59 -Started FoodSpringBootApplication in 9.025 seconds (JVM running for 11.154)
2019-12-12 12:04:16.534 INFO [http-nio-8080-exec-1]o.a.c.c.C.[Tomcat].[localhost].[/foodspringboot].log:173 -Initializing Spring DispatcherServlet 'dispatcherServlet'
2019-12-12 12:04:16.534 INFO [http-nio-8080-exec-1]org.springframework.web.servlet.DispatcherServlet.initServletBean:524 -Initializing Servlet 'dispatcherServlet'
2019-12-12 12:04:16.545 INFO [http-nio-8080-exec-1]org.springframework.web.servlet.DispatcherServlet.initServletBean:546 -Completed initialization in 11 ms
2019-12-12 12:04:17.391 INFO [http-nio-8080-exec-1]io.lettuce.core.EpollProvider.<clinit>:68 -Starting without optional epoll library
2019-12-12 12:04:17.395 INFO [http-nio-8080-exec-1]io.lettuce.core.KqueueProvider.<clinit>:70 -Starting without optional kqueue library
2019-12-12 12:04:39.244 WARN [http-nio-8080-exec-1]o.s.w.s.m.m.annotation.ExceptionHandlerExceptionResolver.logException:198 -Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 172.18.0.2:6300]
2019-12-12 12:25:04.800 INFO [restartedMain]com.wl.foodspringboot.FoodSpringBootApplication.logStarting:50 -Starting FoodSpringBootApplication on DESKTOP-814O8JJ with PID 13808 (E:\Learn\IdeaProjects\FoodSpringBoot\target\classes started by WL in E:\Learn\IdeaProjects\FoodSpringBoot)
2019-12-12 12:25:04.804 INFO [restartedMain]com.wl.foodspringboot.FoodSpringBootApplication.logStartupProfileInfo:647 -No active profile set, falling back to default profiles: default
2019-12-12 12:25:04.841 INFO [restartedMain]o.s.b.devtools.env.DevToolsPropertyDefaultsPostProcessor.logTo:225 -Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
2019-12-12 12:25:04.841 INFO [restartedMain]o.s.b.devtools.env.DevToolsPropertyDefaultsPostProcessor.logTo:225 -For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
2019-12-12 12:25:05.497 INFO [restartedMain]o.s.d.repository.config.RepositoryConfigurationDelegate.multipleStoresDetected:244 -Multiple Spring Data modules found, entering strict repository configuration mode!
2019-12-12 12:25:05.499 INFO [restartedMain]o.s.d.repository.config.RepositoryConfigurationDelegate.registerRepositoriesIn:126 -Bootstrapping Spring Data repositories in DEFAULT mode.
2019-12-12 12:25:05.520 INFO [restartedMain]o.s.d.repository.config.RepositoryConfigurationDelegate.registerRepositoriesIn:182 -Finished Spring Data repository scanning in 10ms. Found 0 repository interfaces.
2019-12-12 12:25:05.834 INFO [restartedMain]o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.postProcessAfterInitialization:330 -Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$75306035] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-12-12 12:25:06.468 INFO [restartedMain]o.s.boot.web.embedded.tomcat.TomcatWebServer.initialize:90 -Tomcat initialized with port(s): 8080 (http)
2019-12-12 12:25:06.484 INFO [restartedMain]org.apache.coyote.http11.Http11NioProtocol.log:173 -Initializing ProtocolHandler ["http-nio-8080"]
2019-12-12 12:25:06.491 INFO [restartedMain]org.apache.catalina.core.StandardService.log:173 -Starting service [Tomcat]
2019-12-12 12:25:06.491 INFO [restartedMain]org.apache.catalina.core.StandardEngine.log:173 -Starting Servlet engine: [Apache Tomcat/9.0.22]
2019-12-12 12:25:06.496 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -An older version [1.2.21] of the APR based Apache Tomcat Native library is installed, while Tomcat recommends a minimum version of [1.2.23]
2019-12-12 12:25:06.497 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -Loaded APR based Apache Tomcat Native library [1.2.21] using APR version [1.6.5].
2019-12-12 12:25:06.497 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
2019-12-12 12:25:06.497 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
2019-12-12 12:25:06.500 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -OpenSSL successfully initialized [OpenSSL 1.1.1a  20 Nov 2018]
2019-12-12 12:25:06.610 INFO [restartedMain]o.a.c.c.C.[Tomcat].[localhost].[/foodspringboot].log:173 -Initializing Spring embedded WebApplicationContext
2019-12-12 12:25:06.610 INFO [restartedMain]org.springframework.web.context.ContextLoader.prepareWebApplicationContext:284 -Root WebApplicationContext: initialization completed in 1769 ms
2019-12-12 12:25:07.061 INFO [restartedMain]org.messaginghub.pooled.jms.JmsPoolConnectionFactory.setConnectionFactory:198 -Provided ConnectionFactory implementation is JMS 2.0+ capable.
2019-12-12 12:25:07.464 INFO [restartedMain]o.s.scheduling.concurrent.ThreadPoolTaskExecutor.initialize:171 -Initializing ExecutorService 'applicationTaskExecutor'
2019-12-12 12:25:07.518 INFO [restartedMain]o.s.b.a.web.servlet.WelcomePageHandlerMapping.<init>:54 -Adding welcome page: class path resource [public/index.html]
2019-12-12 12:25:07.594 WARN [restartedMain]org.thymeleaf.templatemode.TemplateMode.parse:150 -[THYMELEAF][restartedMain] Template Mode 'HTML5' is deprecated. Using Template Mode 'HTML' instead.
2019-12-12 12:25:07.803 INFO [restartedMain]o.s.boot.devtools.autoconfigure.OptionalLiveReloadServer.startServer:57 -LiveReload server is running on port 35729
2019-12-12 12:25:08.114 INFO [restartedMain]org.apache.coyote.http11.Http11NioProtocol.log:173 -Starting ProtocolHandler ["http-nio-8080"]
2019-12-12 12:25:08.141 INFO [restartedMain]o.s.boot.web.embedded.tomcat.TomcatWebServer.start:202 -Tomcat started on port(s): 8080 (http) with context path '/foodspringboot'
2019-12-12 12:25:08.143 INFO [restartedMain]com.wl.foodspringboot.FoodSpringBootApplication.logStarted:59 -Started FoodSpringBootApplication in 3.713 seconds (JVM running for 5.954)
2019-12-12 12:25:26.045 INFO [http-nio-8080-exec-1]o.a.c.c.C.[Tomcat].[localhost].[/foodspringboot].log:173 -Initializing Spring DispatcherServlet 'dispatcherServlet'
2019-12-12 12:25:26.046 INFO [http-nio-8080-exec-1]org.springframework.web.servlet.DispatcherServlet.initServletBean:524 -Initializing Servlet 'dispatcherServlet'
2019-12-12 12:25:26.053 INFO [http-nio-8080-exec-1]org.springframework.web.servlet.DispatcherServlet.initServletBean:546 -Completed initialization in 7 ms
2019-12-12 12:25:26.270 INFO [http-nio-8080-exec-1]io.lettuce.core.EpollProvider.<clinit>:68 -Starting without optional epoll library
2019-12-12 12:25:26.272 INFO [http-nio-8080-exec-1]io.lettuce.core.KqueueProvider.<clinit>:70 -Starting without optional kqueue library
2019-12-12 12:26:22.091 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6300
2019-12-12 12:26:32.123 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6300
2019-12-12 12:26:32.189 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6300
2019-12-12 12:26:42.215 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6300
2019-12-12 12:26:42.289 INFO [lettuce-eventExecutorLoop-1-9]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6300
2019-12-12 12:26:52.314 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6300
2019-12-12 12:26:52.388 INFO [lettuce-eventExecutorLoop-1-11]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6300
2019-12-12 12:27:02.411 WARN [lettuce-nioEventLoop-4-10]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6300
2019-12-12 12:27:02.488 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6300
2019-12-12 12:27:12.511 WARN [lettuce-nioEventLoop-4-12]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6300
2019-12-12 12:27:12.587 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6300
2019-12-12 12:27:22.594 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6300
2019-12-12 12:27:22.689 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6300
2019-12-12 12:27:32.706 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6300
2019-12-12 12:27:32.888 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6300
2019-12-12 12:27:42.903 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6300
2019-12-12 12:27:43.188 INFO [lettuce-eventExecutorLoop-1-9]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6300
2019-12-12 12:27:53.197 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6300
2019-12-12 12:27:53.787 INFO [lettuce-eventExecutorLoop-1-11]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6300
2019-12-12 12:28:03.805 WARN [lettuce-nioEventLoop-4-10]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6300
2019-12-12 12:28:04.888 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6300
2019-12-12 12:28:14.903 WARN [lettuce-nioEventLoop-4-12]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6300
2019-12-12 12:28:22.175 INFO [restartedMain]com.wl.foodspringboot.FoodSpringBootApplication.logStarting:50 -Starting FoodSpringBootApplication on DESKTOP-814O8JJ with PID 8748 (E:\Learn\IdeaProjects\FoodSpringBoot\target\classes started by WL in E:\Learn\IdeaProjects\FoodSpringBoot)
2019-12-12 12:28:22.179 INFO [restartedMain]com.wl.foodspringboot.FoodSpringBootApplication.logStartupProfileInfo:647 -No active profile set, falling back to default profiles: default
2019-12-12 12:28:22.220 INFO [restartedMain]o.s.b.devtools.env.DevToolsPropertyDefaultsPostProcessor.logTo:225 -Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
2019-12-12 12:28:22.220 INFO [restartedMain]o.s.b.devtools.env.DevToolsPropertyDefaultsPostProcessor.logTo:225 -For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
2019-12-12 12:28:22.904 INFO [restartedMain]o.s.d.repository.config.RepositoryConfigurationDelegate.multipleStoresDetected:244 -Multiple Spring Data modules found, entering strict repository configuration mode!
2019-12-12 12:28:22.907 INFO [restartedMain]o.s.d.repository.config.RepositoryConfigurationDelegate.registerRepositoriesIn:126 -Bootstrapping Spring Data repositories in DEFAULT mode.
2019-12-12 12:28:22.931 INFO [restartedMain]o.s.d.repository.config.RepositoryConfigurationDelegate.registerRepositoriesIn:182 -Finished Spring Data repository scanning in 10ms. Found 0 repository interfaces.
2019-12-12 12:28:23.264 INFO [restartedMain]o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.postProcessAfterInitialization:330 -Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$2eca6bcd] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-12-12 12:28:23.604 INFO [restartedMain]o.s.boot.web.embedded.tomcat.TomcatWebServer.initialize:90 -Tomcat initialized with port(s): 8080 (http)
2019-12-12 12:28:23.635 INFO [restartedMain]org.apache.coyote.http11.Http11NioProtocol.log:173 -Initializing ProtocolHandler ["http-nio-8080"]
2019-12-12 12:28:23.654 INFO [restartedMain]org.apache.catalina.core.StandardService.log:173 -Starting service [Tomcat]
2019-12-12 12:28:23.655 INFO [restartedMain]org.apache.catalina.core.StandardEngine.log:173 -Starting Servlet engine: [Apache Tomcat/9.0.22]
2019-12-12 12:28:23.668 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -An older version [1.2.21] of the APR based Apache Tomcat Native library is installed, while Tomcat recommends a minimum version of [1.2.23]
2019-12-12 12:28:23.669 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -Loaded APR based Apache Tomcat Native library [1.2.21] using APR version [1.6.5].
2019-12-12 12:28:23.669 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
2019-12-12 12:28:23.669 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
2019-12-12 12:28:23.675 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -OpenSSL successfully initialized [OpenSSL 1.1.1a  20 Nov 2018]
2019-12-12 12:28:23.817 INFO [restartedMain]o.a.c.c.C.[Tomcat].[localhost].[/foodspringboot].log:173 -Initializing Spring embedded WebApplicationContext
2019-12-12 12:28:23.818 INFO [restartedMain]org.springframework.web.context.ContextLoader.prepareWebApplicationContext:284 -Root WebApplicationContext: initialization completed in 1597 ms
2019-12-12 12:28:24.178 INFO [restartedMain]org.messaginghub.pooled.jms.JmsPoolConnectionFactory.setConnectionFactory:198 -Provided ConnectionFactory implementation is JMS 2.0+ capable.
2019-12-12 12:28:24.792 INFO [restartedMain]o.s.scheduling.concurrent.ThreadPoolTaskExecutor.initialize:171 -Initializing ExecutorService 'applicationTaskExecutor'
2019-12-12 12:28:24.849 INFO [restartedMain]o.s.b.a.web.servlet.WelcomePageHandlerMapping.<init>:54 -Adding welcome page: class path resource [public/index.html]
2019-12-12 12:28:24.890 WARN [restartedMain]org.thymeleaf.templatemode.TemplateMode.parse:150 -[THYMELEAF][restartedMain] Template Mode 'HTML5' is deprecated. Using Template Mode 'HTML' instead.
2019-12-12 12:28:25.103 INFO [restartedMain]o.s.boot.devtools.autoconfigure.OptionalLiveReloadServer.startServer:57 -LiveReload server is running on port 35729
2019-12-12 12:28:25.361 INFO [restartedMain]org.apache.coyote.http11.Http11NioProtocol.log:173 -Starting ProtocolHandler ["http-nio-8080"]
2019-12-12 12:28:25.381 INFO [restartedMain]o.s.boot.web.embedded.tomcat.TomcatWebServer.start:202 -Tomcat started on port(s): 8080 (http) with context path '/foodspringboot'
2019-12-12 12:28:25.384 INFO [restartedMain]com.wl.foodspringboot.FoodSpringBootApplication.logStarted:59 -Started FoodSpringBootApplication in 3.57 seconds (JVM running for 4.806)
2019-12-12 12:28:30.585 INFO [http-nio-8080-exec-1]o.a.c.c.C.[Tomcat].[localhost].[/foodspringboot].log:173 -Initializing Spring DispatcherServlet 'dispatcherServlet'
2019-12-12 12:28:30.585 INFO [http-nio-8080-exec-1]org.springframework.web.servlet.DispatcherServlet.initServletBean:524 -Initializing Servlet 'dispatcherServlet'
2019-12-12 12:28:30.594 INFO [http-nio-8080-exec-1]org.springframework.web.servlet.DispatcherServlet.initServletBean:546 -Completed initialization in 9 ms
2019-12-12 12:28:30.791 INFO [http-nio-8080-exec-1]io.lettuce.core.EpollProvider.<clinit>:68 -Starting without optional epoll library
2019-12-12 12:28:30.795 INFO [http-nio-8080-exec-1]io.lettuce.core.KqueueProvider.<clinit>:70 -Starting without optional kqueue library
2019-12-12 12:28:52.255 WARN [http-nio-8080-exec-1]o.s.w.s.m.m.annotation.ExceptionHandlerExceptionResolver.logException:198 -Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 192.168.56.101:6300]
2019-12-12 12:30:47.017 INFO [restartedMain]com.wl.foodspringboot.FoodSpringBootApplication.logStarting:50 -Starting FoodSpringBootApplication on DESKTOP-814O8JJ with PID 7156 (E:\Learn\IdeaProjects\FoodSpringBoot\target\classes started by WL in E:\Learn\IdeaProjects\FoodSpringBoot)
2019-12-12 12:30:47.020 INFO [restartedMain]com.wl.foodspringboot.FoodSpringBootApplication.logStartupProfileInfo:647 -No active profile set, falling back to default profiles: default
2019-12-12 12:30:47.062 INFO [restartedMain]o.s.b.devtools.env.DevToolsPropertyDefaultsPostProcessor.logTo:225 -Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
2019-12-12 12:30:47.062 INFO [restartedMain]o.s.b.devtools.env.DevToolsPropertyDefaultsPostProcessor.logTo:225 -For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
2019-12-12 12:30:47.820 INFO [restartedMain]o.s.d.repository.config.RepositoryConfigurationDelegate.multipleStoresDetected:244 -Multiple Spring Data modules found, entering strict repository configuration mode!
2019-12-12 12:30:47.822 INFO [restartedMain]o.s.d.repository.config.RepositoryConfigurationDelegate.registerRepositoriesIn:126 -Bootstrapping Spring Data repositories in DEFAULT mode.
2019-12-12 12:30:47.843 INFO [restartedMain]o.s.d.repository.config.RepositoryConfigurationDelegate.registerRepositoriesIn:182 -Finished Spring Data repository scanning in 9ms. Found 0 repository interfaces.
2019-12-12 12:30:48.167 INFO [restartedMain]o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.postProcessAfterInitialization:330 -Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$c217080] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-12-12 12:30:48.662 INFO [restartedMain]o.s.boot.web.embedded.tomcat.TomcatWebServer.initialize:90 -Tomcat initialized with port(s): 8080 (http)
2019-12-12 12:30:48.673 INFO [restartedMain]org.apache.coyote.http11.Http11NioProtocol.log:173 -Initializing ProtocolHandler ["http-nio-8080"]
2019-12-12 12:30:48.686 INFO [restartedMain]org.apache.catalina.core.StandardService.log:173 -Starting service [Tomcat]
2019-12-12 12:30:48.687 INFO [restartedMain]org.apache.catalina.core.StandardEngine.log:173 -Starting Servlet engine: [Apache Tomcat/9.0.22]
2019-12-12 12:30:48.692 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -An older version [1.2.21] of the APR based Apache Tomcat Native library is installed, while Tomcat recommends a minimum version of [1.2.23]
2019-12-12 12:30:48.693 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -Loaded APR based Apache Tomcat Native library [1.2.21] using APR version [1.6.5].
2019-12-12 12:30:48.693 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
2019-12-12 12:30:48.693 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
2019-12-12 12:30:48.697 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -OpenSSL successfully initialized [OpenSSL 1.1.1a  20 Nov 2018]
2019-12-12 12:30:48.813 INFO [restartedMain]o.a.c.c.C.[Tomcat].[localhost].[/foodspringboot].log:173 -Initializing Spring embedded WebApplicationContext
2019-12-12 12:30:48.814 INFO [restartedMain]org.springframework.web.context.ContextLoader.prepareWebApplicationContext:284 -Root WebApplicationContext: initialization completed in 1751 ms
2019-12-12 12:30:49.185 INFO [restartedMain]org.messaginghub.pooled.jms.JmsPoolConnectionFactory.setConnectionFactory:198 -Provided ConnectionFactory implementation is JMS 2.0+ capable.
2019-12-12 12:30:49.630 INFO [restartedMain]o.s.scheduling.concurrent.ThreadPoolTaskExecutor.initialize:171 -Initializing ExecutorService 'applicationTaskExecutor'
2019-12-12 12:30:49.696 INFO [restartedMain]o.s.b.a.web.servlet.WelcomePageHandlerMapping.<init>:54 -Adding welcome page: class path resource [public/index.html]
2019-12-12 12:30:49.743 WARN [restartedMain]org.thymeleaf.templatemode.TemplateMode.parse:150 -[THYMELEAF][restartedMain] Template Mode 'HTML5' is deprecated. Using Template Mode 'HTML' instead.
2019-12-12 12:30:50.010 INFO [restartedMain]o.s.boot.devtools.autoconfigure.OptionalLiveReloadServer.startServer:57 -LiveReload server is running on port 35729
2019-12-12 12:30:50.244 INFO [restartedMain]org.apache.coyote.http11.Http11NioProtocol.log:173 -Starting ProtocolHandler ["http-nio-8080"]
2019-12-12 12:30:50.264 INFO [restartedMain]o.s.boot.web.embedded.tomcat.TomcatWebServer.start:202 -Tomcat started on port(s): 8080 (http) with context path '/foodspringboot'
2019-12-12 12:30:50.267 INFO [restartedMain]com.wl.foodspringboot.FoodSpringBootApplication.logStarted:59 -Started FoodSpringBootApplication in 3.627 seconds (JVM running for 5.491)
2019-12-12 12:30:57.405 INFO [http-nio-8080-exec-1]o.a.c.c.C.[Tomcat].[localhost].[/foodspringboot].log:173 -Initializing Spring DispatcherServlet 'dispatcherServlet'
2019-12-12 12:30:57.405 INFO [http-nio-8080-exec-1]org.springframework.web.servlet.DispatcherServlet.initServletBean:524 -Initializing Servlet 'dispatcherServlet'
2019-12-12 12:30:57.411 INFO [http-nio-8080-exec-1]org.springframework.web.servlet.DispatcherServlet.initServletBean:546 -Completed initialization in 6 ms
2019-12-12 12:30:57.561 INFO [http-nio-8080-exec-1]io.lettuce.core.EpollProvider.<clinit>:68 -Starting without optional epoll library
2019-12-12 12:30:57.562 INFO [http-nio-8080-exec-1]io.lettuce.core.KqueueProvider.<clinit>:70 -Starting without optional kqueue library
2019-12-12 12:43:41.590 INFO [restartedMain]com.wl.foodspringboot.FoodSpringBootApplication.logStarting:50 -Starting FoodSpringBootApplication on DESKTOP-814O8JJ with PID 15484 (E:\Learn\IdeaProjects\FoodSpringBoot\target\classes started by WL in E:\Learn\IdeaProjects\FoodSpringBoot)
2019-12-12 12:43:41.594 INFO [restartedMain]com.wl.foodspringboot.FoodSpringBootApplication.logStartupProfileInfo:647 -No active profile set, falling back to default profiles: default
2019-12-12 12:43:41.641 INFO [restartedMain]o.s.b.devtools.env.DevToolsPropertyDefaultsPostProcessor.logTo:225 -Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
2019-12-12 12:43:41.642 INFO [restartedMain]o.s.b.devtools.env.DevToolsPropertyDefaultsPostProcessor.logTo:225 -For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
2019-12-12 12:43:42.329 INFO [restartedMain]o.s.d.repository.config.RepositoryConfigurationDelegate.multipleStoresDetected:244 -Multiple Spring Data modules found, entering strict repository configuration mode!
2019-12-12 12:43:42.331 INFO [restartedMain]o.s.d.repository.config.RepositoryConfigurationDelegate.registerRepositoriesIn:126 -Bootstrapping Spring Data repositories in DEFAULT mode.
2019-12-12 12:43:42.352 INFO [restartedMain]o.s.d.repository.config.RepositoryConfigurationDelegate.registerRepositoriesIn:182 -Finished Spring Data repository scanning in 9ms. Found 0 repository interfaces.
2019-12-12 12:43:42.664 INFO [restartedMain]o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.postProcessAfterInitialization:330 -Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$c36c4809] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-12-12 12:43:43.265 INFO [restartedMain]o.s.boot.web.embedded.tomcat.TomcatWebServer.initialize:90 -Tomcat initialized with port(s): 8080 (http)
2019-12-12 12:43:43.287 INFO [restartedMain]org.apache.coyote.http11.Http11NioProtocol.log:173 -Initializing ProtocolHandler ["http-nio-8080"]
2019-12-12 12:43:43.295 INFO [restartedMain]org.apache.catalina.core.StandardService.log:173 -Starting service [Tomcat]
2019-12-12 12:43:43.296 INFO [restartedMain]org.apache.catalina.core.StandardEngine.log:173 -Starting Servlet engine: [Apache Tomcat/9.0.22]
2019-12-12 12:43:43.302 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -An older version [1.2.21] of the APR based Apache Tomcat Native library is installed, while Tomcat recommends a minimum version of [1.2.23]
2019-12-12 12:43:43.303 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -Loaded APR based Apache Tomcat Native library [1.2.21] using APR version [1.6.5].
2019-12-12 12:43:43.303 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
2019-12-12 12:43:43.303 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
2019-12-12 12:43:43.307 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -OpenSSL successfully initialized [OpenSSL 1.1.1a  20 Nov 2018]
2019-12-12 12:43:43.418 INFO [restartedMain]o.a.c.c.C.[Tomcat].[localhost].[/foodspringboot].log:173 -Initializing Spring embedded WebApplicationContext
2019-12-12 12:43:43.419 INFO [restartedMain]org.springframework.web.context.ContextLoader.prepareWebApplicationContext:284 -Root WebApplicationContext: initialization completed in 1777 ms
2019-12-12 12:43:43.721 INFO [restartedMain]org.messaginghub.pooled.jms.JmsPoolConnectionFactory.setConnectionFactory:198 -Provided ConnectionFactory implementation is JMS 2.0+ capable.
2019-12-12 12:43:44.234 INFO [restartedMain]o.s.scheduling.concurrent.ThreadPoolTaskExecutor.initialize:171 -Initializing ExecutorService 'applicationTaskExecutor'
2019-12-12 12:43:44.292 INFO [restartedMain]o.s.b.a.web.servlet.WelcomePageHandlerMapping.<init>:54 -Adding welcome page: class path resource [public/index.html]
2019-12-12 12:43:44.329 WARN [restartedMain]org.thymeleaf.templatemode.TemplateMode.parse:150 -[THYMELEAF][restartedMain] Template Mode 'HTML5' is deprecated. Using Template Mode 'HTML' instead.
2019-12-12 12:43:44.540 INFO [restartedMain]o.s.boot.devtools.autoconfigure.OptionalLiveReloadServer.startServer:57 -LiveReload server is running on port 35729
2019-12-12 12:43:44.907 INFO [restartedMain]org.apache.coyote.http11.Http11NioProtocol.log:173 -Starting ProtocolHandler ["http-nio-8080"]
2019-12-12 12:43:44.929 INFO [restartedMain]o.s.boot.web.embedded.tomcat.TomcatWebServer.start:202 -Tomcat started on port(s): 8080 (http) with context path '/foodspringboot'
2019-12-12 12:43:44.932 INFO [restartedMain]com.wl.foodspringboot.FoodSpringBootApplication.logStarted:59 -Started FoodSpringBootApplication in 3.711 seconds (JVM running for 4.902)
2019-12-12 12:43:56.435 INFO [http-nio-8080-exec-1]o.a.c.c.C.[Tomcat].[localhost].[/foodspringboot].log:173 -Initializing Spring DispatcherServlet 'dispatcherServlet'
2019-12-12 12:43:56.435 INFO [http-nio-8080-exec-1]org.springframework.web.servlet.DispatcherServlet.initServletBean:524 -Initializing Servlet 'dispatcherServlet'
2019-12-12 12:43:56.443 INFO [http-nio-8080-exec-1]org.springframework.web.servlet.DispatcherServlet.initServletBean:546 -Completed initialization in 7 ms
2019-12-12 12:43:56.620 INFO [http-nio-8080-exec-1]io.lettuce.core.EpollProvider.<clinit>:68 -Starting without optional epoll library
2019-12-12 12:43:56.622 INFO [http-nio-8080-exec-1]io.lettuce.core.KqueueProvider.<clinit>:70 -Starting without optional kqueue library
2019-12-12 12:44:17.943 WARN [http-nio-8080-exec-1]o.s.w.s.m.m.annotation.ExceptionHandlerExceptionResolver.logException:198 -Resolved [org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 172.18.0.2:6300]
2019-12-12 13:14:20.374 INFO [restartedMain]com.wl.foodspringboot.FoodSpringBootApplication.logStarting:50 -Starting FoodSpringBootApplication on DESKTOP-814O8JJ with PID 11380 (E:\Learn\IdeaProjects\FoodSpringBoot\target\classes started by WL in E:\Learn\IdeaProjects\FoodSpringBoot)
2019-12-12 13:14:20.376 INFO [restartedMain]com.wl.foodspringboot.FoodSpringBootApplication.logStartupProfileInfo:647 -No active profile set, falling back to default profiles: default
2019-12-12 13:14:20.409 INFO [restartedMain]o.s.b.devtools.env.DevToolsPropertyDefaultsPostProcessor.logTo:225 -Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
2019-12-12 13:14:20.409 INFO [restartedMain]o.s.b.devtools.env.DevToolsPropertyDefaultsPostProcessor.logTo:225 -For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
2019-12-12 13:14:20.959 INFO [restartedMain]o.s.d.repository.config.RepositoryConfigurationDelegate.multipleStoresDetected:244 -Multiple Spring Data modules found, entering strict repository configuration mode!
2019-12-12 13:14:20.960 INFO [restartedMain]o.s.d.repository.config.RepositoryConfigurationDelegate.registerRepositoriesIn:126 -Bootstrapping Spring Data repositories in DEFAULT mode.
2019-12-12 13:14:20.977 INFO [restartedMain]o.s.d.repository.config.RepositoryConfigurationDelegate.registerRepositoriesIn:182 -Finished Spring Data repository scanning in 7ms. Found 0 repository interfaces.
2019-12-12 13:14:21.220 INFO [restartedMain]o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.postProcessAfterInitialization:330 -Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$a1c4b943] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-12-12 13:14:21.448 INFO [restartedMain]o.s.boot.web.embedded.tomcat.TomcatWebServer.initialize:90 -Tomcat initialized with port(s): 8080 (http)
2019-12-12 13:14:21.458 INFO [restartedMain]org.apache.coyote.http11.Http11NioProtocol.log:173 -Initializing ProtocolHandler ["http-nio-8080"]
2019-12-12 13:14:21.464 INFO [restartedMain]org.apache.catalina.core.StandardService.log:173 -Starting service [Tomcat]
2019-12-12 13:14:21.465 INFO [restartedMain]org.apache.catalina.core.StandardEngine.log:173 -Starting Servlet engine: [Apache Tomcat/9.0.22]
2019-12-12 13:14:21.469 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -An older version [1.2.21] of the APR based Apache Tomcat Native library is installed, while Tomcat recommends a minimum version of [1.2.23]
2019-12-12 13:14:21.469 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -Loaded APR based Apache Tomcat Native library [1.2.21] using APR version [1.6.5].
2019-12-12 13:14:21.470 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
2019-12-12 13:14:21.470 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
2019-12-12 13:14:21.472 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -OpenSSL successfully initialized [OpenSSL 1.1.1a  20 Nov 2018]
2019-12-12 13:14:21.555 INFO [restartedMain]o.a.c.c.C.[Tomcat].[localhost].[/foodspringboot].log:173 -Initializing Spring embedded WebApplicationContext
2019-12-12 13:14:21.556 INFO [restartedMain]org.springframework.web.context.ContextLoader.prepareWebApplicationContext:284 -Root WebApplicationContext: initialization completed in 1147 ms
2019-12-12 13:14:21.785 INFO [restartedMain]org.messaginghub.pooled.jms.JmsPoolConnectionFactory.setConnectionFactory:198 -Provided ConnectionFactory implementation is JMS 2.0+ capable.
2019-12-12 13:14:22.094 INFO [restartedMain]o.s.scheduling.concurrent.ThreadPoolTaskExecutor.initialize:171 -Initializing ExecutorService 'applicationTaskExecutor'
2019-12-12 13:14:22.135 INFO [restartedMain]o.s.b.a.web.servlet.WelcomePageHandlerMapping.<init>:54 -Adding welcome page: class path resource [public/index.html]
2019-12-12 13:14:22.165 WARN [restartedMain]org.thymeleaf.templatemode.TemplateMode.parse:150 -[THYMELEAF][restartedMain] Template Mode 'HTML5' is deprecated. Using Template Mode 'HTML' instead.
2019-12-12 13:14:22.325 INFO [restartedMain]o.s.boot.devtools.autoconfigure.OptionalLiveReloadServer.startServer:57 -LiveReload server is running on port 35729
2019-12-12 13:14:22.551 INFO [restartedMain]org.apache.coyote.http11.Http11NioProtocol.log:173 -Starting ProtocolHandler ["http-nio-8080"]
2019-12-12 13:14:22.568 INFO [restartedMain]o.s.boot.web.embedded.tomcat.TomcatWebServer.start:202 -Tomcat started on port(s): 8080 (http) with context path '/foodspringboot'
2019-12-12 13:14:22.570 INFO [restartedMain]com.wl.foodspringboot.FoodSpringBootApplication.logStarted:59 -Started FoodSpringBootApplication in 2.502 seconds (JVM running for 3.402)
2019-12-12 13:14:40.058 INFO [http-nio-8080-exec-1]o.a.c.c.C.[Tomcat].[localhost].[/foodspringboot].log:173 -Initializing Spring DispatcherServlet 'dispatcherServlet'
2019-12-12 13:14:40.058 INFO [http-nio-8080-exec-1]org.springframework.web.servlet.DispatcherServlet.initServletBean:524 -Initializing Servlet 'dispatcherServlet'
2019-12-12 13:14:40.063 INFO [http-nio-8080-exec-1]org.springframework.web.servlet.DispatcherServlet.initServletBean:546 -Completed initialization in 5 ms
2019-12-12 13:14:40.176 INFO [http-nio-8080-exec-1]io.lettuce.core.EpollProvider.<clinit>:68 -Starting without optional epoll library
2019-12-12 13:14:40.177 INFO [http-nio-8080-exec-1]io.lettuce.core.KqueueProvider.<clinit>:70 -Starting without optional kqueue library
2019-12-12 13:19:05.845 INFO [restartedMain]com.wl.foodspringboot.FoodSpringBootApplication.logStarting:50 -Starting FoodSpringBootApplication on DESKTOP-814O8JJ with PID 10540 (E:\Learn\IdeaProjects\FoodSpringBoot\target\classes started by WL in E:\Learn\IdeaProjects\FoodSpringBoot)
2019-12-12 13:19:05.848 INFO [restartedMain]com.wl.foodspringboot.FoodSpringBootApplication.logStartupProfileInfo:647 -No active profile set, falling back to default profiles: default
2019-12-12 13:19:05.886 INFO [restartedMain]o.s.b.devtools.env.DevToolsPropertyDefaultsPostProcessor.logTo:225 -Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
2019-12-12 13:19:05.886 INFO [restartedMain]o.s.b.devtools.env.DevToolsPropertyDefaultsPostProcessor.logTo:225 -For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
2019-12-12 13:19:06.429 INFO [restartedMain]o.s.d.repository.config.RepositoryConfigurationDelegate.multipleStoresDetected:244 -Multiple Spring Data modules found, entering strict repository configuration mode!
2019-12-12 13:19:06.431 INFO [restartedMain]o.s.d.repository.config.RepositoryConfigurationDelegate.registerRepositoriesIn:126 -Bootstrapping Spring Data repositories in DEFAULT mode.
2019-12-12 13:19:06.447 INFO [restartedMain]o.s.d.repository.config.RepositoryConfigurationDelegate.registerRepositoriesIn:182 -Finished Spring Data repository scanning in 8ms. Found 0 repository interfaces.
2019-12-12 13:19:06.680 INFO [restartedMain]o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.postProcessAfterInitialization:330 -Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$d2f919ac] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-12-12 13:19:06.911 INFO [restartedMain]o.s.boot.web.embedded.tomcat.TomcatWebServer.initialize:90 -Tomcat initialized with port(s): 8080 (http)
2019-12-12 13:19:06.920 INFO [restartedMain]org.apache.coyote.http11.Http11NioProtocol.log:173 -Initializing ProtocolHandler ["http-nio-8080"]
2019-12-12 13:19:06.926 INFO [restartedMain]org.apache.catalina.core.StandardService.log:173 -Starting service [Tomcat]
2019-12-12 13:19:06.926 INFO [restartedMain]org.apache.catalina.core.StandardEngine.log:173 -Starting Servlet engine: [Apache Tomcat/9.0.22]
2019-12-12 13:19:06.930 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -An older version [1.2.21] of the APR based Apache Tomcat Native library is installed, while Tomcat recommends a minimum version of [1.2.23]
2019-12-12 13:19:06.931 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -Loaded APR based Apache Tomcat Native library [1.2.21] using APR version [1.6.5].
2019-12-12 13:19:06.931 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
2019-12-12 13:19:06.931 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
2019-12-12 13:19:06.934 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -OpenSSL successfully initialized [OpenSSL 1.1.1a  20 Nov 2018]
2019-12-12 13:19:07.017 INFO [restartedMain]o.a.c.c.C.[Tomcat].[localhost].[/foodspringboot].log:173 -Initializing Spring embedded WebApplicationContext
2019-12-12 13:19:07.017 INFO [restartedMain]org.springframework.web.context.ContextLoader.prepareWebApplicationContext:284 -Root WebApplicationContext: initialization completed in 1131 ms
2019-12-12 13:19:07.250 INFO [restartedMain]org.messaginghub.pooled.jms.JmsPoolConnectionFactory.setConnectionFactory:198 -Provided ConnectionFactory implementation is JMS 2.0+ capable.
2019-12-12 13:19:07.579 INFO [restartedMain]o.s.scheduling.concurrent.ThreadPoolTaskExecutor.initialize:171 -Initializing ExecutorService 'applicationTaskExecutor'
2019-12-12 13:19:07.623 INFO [restartedMain]o.s.b.a.web.servlet.WelcomePageHandlerMapping.<init>:54 -Adding welcome page: class path resource [public/index.html]
2019-12-12 13:19:07.652 WARN [restartedMain]org.thymeleaf.templatemode.TemplateMode.parse:150 -[THYMELEAF][restartedMain] Template Mode 'HTML5' is deprecated. Using Template Mode 'HTML' instead.
2019-12-12 13:19:07.811 INFO [restartedMain]o.s.boot.devtools.autoconfigure.OptionalLiveReloadServer.startServer:57 -LiveReload server is running on port 35729
2019-12-12 13:19:08.116 INFO [restartedMain]org.apache.coyote.http11.Http11NioProtocol.log:173 -Starting ProtocolHandler ["http-nio-8080"]
2019-12-12 13:19:08.131 INFO [restartedMain]o.s.boot.web.embedded.tomcat.TomcatWebServer.start:202 -Tomcat started on port(s): 8080 (http) with context path '/foodspringboot'
2019-12-12 13:19:08.133 INFO [restartedMain]com.wl.foodspringboot.FoodSpringBootApplication.logStarted:59 -Started FoodSpringBootApplication in 2.582 seconds (JVM running for 3.468)
2019-12-12 13:19:18.597 INFO [http-nio-8080-exec-1]o.a.c.c.C.[Tomcat].[localhost].[/foodspringboot].log:173 -Initializing Spring DispatcherServlet 'dispatcherServlet'
2019-12-12 13:19:18.597 INFO [http-nio-8080-exec-1]org.springframework.web.servlet.DispatcherServlet.initServletBean:524 -Initializing Servlet 'dispatcherServlet'
2019-12-12 13:19:18.603 INFO [http-nio-8080-exec-1]org.springframework.web.servlet.DispatcherServlet.initServletBean:546 -Completed initialization in 6 ms
2019-12-12 13:19:18.726 INFO [http-nio-8080-exec-1]io.lettuce.core.EpollProvider.<clinit>:68 -Starting without optional epoll library
2019-12-12 13:19:18.727 INFO [http-nio-8080-exec-1]io.lettuce.core.KqueueProvider.<clinit>:70 -Starting without optional kqueue library
2019-12-12 13:19:57.379 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6300
2019-12-12 13:20:07.393 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6300
2019-12-12 13:20:07.478 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6300
2019-12-12 13:20:17.501 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6300
2019-12-12 13:20:17.579 INFO [lettuce-eventExecutorLoop-1-9]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6300
2019-12-12 13:20:27.601 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6300
2019-12-12 13:20:27.678 INFO [lettuce-eventExecutorLoop-1-11]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6300
2019-12-12 13:20:37.705 WARN [lettuce-nioEventLoop-4-10]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6300
2019-12-12 13:20:37.778 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6300
2019-12-12 13:20:37.802 INFO [lettuce-nioEventLoop-4-12]io.lettuce.core.protocol.ReconnectionHandler.lambda$null$3:177 -Reconnected to 192.168.56.101:6301
2019-12-12 13:35:48.878 INFO [lettuce-eventExecutorLoop-1-10]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6301
2019-12-12 13:35:58.885 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 13:35:58.977 INFO [lettuce-eventExecutorLoop-1-12]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6301
2019-12-12 13:36:08.991 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 13:36:09.078 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6301
2019-12-12 13:36:19.097 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 13:36:19.179 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6301
2019-12-12 13:36:29.197 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 13:36:29.277 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6301
2019-12-12 13:36:39.290 WARN [lettuce-nioEventLoop-4-10]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 13:36:39.378 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6301
2019-12-12 13:36:49.396 WARN [lettuce-nioEventLoop-4-12]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 13:36:49.477 INFO [lettuce-eventExecutorLoop-1-10]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6301
2019-12-12 13:36:59.492 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 13:36:59.678 INFO [lettuce-eventExecutorLoop-1-12]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6301
2019-12-12 13:37:09.695 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 13:37:09.977 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6301
2019-12-12 13:37:19.992 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 13:37:20.578 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6301
2019-12-12 13:37:30.595 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 13:37:31.678 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6301
2019-12-12 13:37:41.682 WARN [lettuce-nioEventLoop-4-10]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 13:37:43.779 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6301
2019-12-12 13:37:53.784 WARN [lettuce-nioEventLoop-4-12]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 13:37:57.978 INFO [lettuce-eventExecutorLoop-1-10]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6301
2019-12-12 13:38:07.993 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 13:38:16.278 INFO [lettuce-eventExecutorLoop-1-12]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6301
2019-12-12 13:38:26.287 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 13:38:42.678 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6301
2019-12-12 13:38:52.682 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 13:39:22.777 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6301
2019-12-12 13:39:32.796 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 13:40:02.878 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6301
2019-12-12 13:40:12.884 WARN [lettuce-nioEventLoop-4-10]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 13:40:42.978 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6301
2019-12-12 13:40:52.983 WARN [lettuce-nioEventLoop-4-12]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 13:41:23.078 INFO [lettuce-eventExecutorLoop-1-10]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6301
2019-12-12 13:41:33.093 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 13:42:03.177 INFO [lettuce-eventExecutorLoop-1-12]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6301
2019-12-12 13:42:13.194 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 13:42:43.277 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6301
2019-12-12 13:42:43.282 INFO [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ReconnectionHandler.lambda$null$3:177 -Reconnected to 192.168.56.101:6300
2019-12-12 13:55:10.578 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6300
2019-12-12 13:55:20.583 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6300
2019-12-12 13:55:20.677 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6300
2019-12-12 13:55:30.695 WARN [lettuce-nioEventLoop-4-10]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6300
2019-12-12 13:55:30.778 INFO [lettuce-eventExecutorLoop-1-9]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6300
2019-12-12 13:55:40.795 WARN [lettuce-nioEventLoop-4-12]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6300
2019-12-12 13:55:40.879 INFO [lettuce-eventExecutorLoop-1-11]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6300
2019-12-12 13:55:50.887 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6300
2019-12-12 13:55:50.978 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6300
2019-12-12 13:55:50.996 INFO [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ReconnectionHandler.lambda$null$3:177 -Reconnected to 192.168.56.101:6301
2019-12-12 13:56:37.777 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6301
2019-12-12 13:56:47.783 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 13:56:47.879 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6301
2019-12-12 13:56:57.884 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 13:56:57.978 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6301
2019-12-12 13:57:07.991 WARN [lettuce-nioEventLoop-4-10]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 13:57:08.078 INFO [lettuce-eventExecutorLoop-1-10]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6301
2019-12-12 13:57:18.085 WARN [lettuce-nioEventLoop-4-12]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 13:57:18.179 INFO [lettuce-eventExecutorLoop-1-12]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6301
2019-12-12 13:57:18.197 INFO [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ReconnectionHandler.lambda$null$3:177 -Reconnected to 192.168.56.101:6301
2019-12-12 14:02:51.757 INFO [restartedMain]com.wl.foodspringboot.FoodSpringBootApplication.logStarting:50 -Starting FoodSpringBootApplication on DESKTOP-814O8JJ with PID 6516 (E:\Learn\IdeaProjects\FoodSpringBoot\target\classes started by WL in E:\Learn\IdeaProjects\FoodSpringBoot)
2019-12-12 14:02:51.760 INFO [restartedMain]com.wl.foodspringboot.FoodSpringBootApplication.logStartupProfileInfo:647 -No active profile set, falling back to default profiles: default
2019-12-12 14:02:51.799 INFO [restartedMain]o.s.b.devtools.env.DevToolsPropertyDefaultsPostProcessor.logTo:225 -Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
2019-12-12 14:02:51.799 INFO [restartedMain]o.s.b.devtools.env.DevToolsPropertyDefaultsPostProcessor.logTo:225 -For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
2019-12-12 14:02:52.449 INFO [restartedMain]o.s.d.repository.config.RepositoryConfigurationDelegate.multipleStoresDetected:244 -Multiple Spring Data modules found, entering strict repository configuration mode!
2019-12-12 14:02:52.451 INFO [restartedMain]o.s.d.repository.config.RepositoryConfigurationDelegate.registerRepositoriesIn:126 -Bootstrapping Spring Data repositories in DEFAULT mode.
2019-12-12 14:02:52.466 INFO [restartedMain]o.s.d.repository.config.RepositoryConfigurationDelegate.registerRepositoriesIn:182 -Finished Spring Data repository scanning in 7ms. Found 0 repository interfaces.
2019-12-12 14:02:52.712 INFO [restartedMain]o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.postProcessAfterInitialization:330 -Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$dcacba7e] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-12-12 14:02:52.940 INFO [restartedMain]o.s.boot.web.embedded.tomcat.TomcatWebServer.initialize:90 -Tomcat initialized with port(s): 8080 (http)
2019-12-12 14:02:52.949 INFO [restartedMain]org.apache.coyote.http11.Http11NioProtocol.log:173 -Initializing ProtocolHandler ["http-nio-8080"]
2019-12-12 14:02:52.953 INFO [restartedMain]org.apache.catalina.core.StandardService.log:173 -Starting service [Tomcat]
2019-12-12 14:02:52.954 INFO [restartedMain]org.apache.catalina.core.StandardEngine.log:173 -Starting Servlet engine: [Apache Tomcat/9.0.22]
2019-12-12 14:02:52.958 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -An older version [1.2.21] of the APR based Apache Tomcat Native library is installed, while Tomcat recommends a minimum version of [1.2.23]
2019-12-12 14:02:52.959 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -Loaded APR based Apache Tomcat Native library [1.2.21] using APR version [1.6.5].
2019-12-12 14:02:52.959 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
2019-12-12 14:02:52.959 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
2019-12-12 14:02:52.962 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -OpenSSL successfully initialized [OpenSSL 1.1.1a  20 Nov 2018]
2019-12-12 14:02:53.046 INFO [restartedMain]o.a.c.c.C.[Tomcat].[localhost].[/foodspringboot].log:173 -Initializing Spring embedded WebApplicationContext
2019-12-12 14:02:53.046 INFO [restartedMain]org.springframework.web.context.ContextLoader.prepareWebApplicationContext:284 -Root WebApplicationContext: initialization completed in 1247 ms
2019-12-12 14:02:53.271 INFO [restartedMain]org.messaginghub.pooled.jms.JmsPoolConnectionFactory.setConnectionFactory:198 -Provided ConnectionFactory implementation is JMS 2.0+ capable.
2019-12-12 14:02:53.578 INFO [restartedMain]o.s.scheduling.concurrent.ThreadPoolTaskExecutor.initialize:171 -Initializing ExecutorService 'applicationTaskExecutor'
2019-12-12 14:02:53.618 INFO [restartedMain]o.s.b.a.web.servlet.WelcomePageHandlerMapping.<init>:54 -Adding welcome page: class path resource [public/index.html]
2019-12-12 14:02:53.648 WARN [restartedMain]org.thymeleaf.templatemode.TemplateMode.parse:150 -[THYMELEAF][restartedMain] Template Mode 'HTML5' is deprecated. Using Template Mode 'HTML' instead.
2019-12-12 14:02:53.806 INFO [restartedMain]o.s.boot.devtools.autoconfigure.OptionalLiveReloadServer.startServer:57 -LiveReload server is running on port 35729
2019-12-12 14:02:54.021 INFO [restartedMain]org.apache.coyote.http11.Http11NioProtocol.log:173 -Starting ProtocolHandler ["http-nio-8080"]
2019-12-12 14:02:54.038 INFO [restartedMain]o.s.boot.web.embedded.tomcat.TomcatWebServer.start:202 -Tomcat started on port(s): 8080 (http) with context path '/foodspringboot'
2019-12-12 14:02:54.041 INFO [restartedMain]com.wl.foodspringboot.FoodSpringBootApplication.logStarted:59 -Started FoodSpringBootApplication in 2.56 seconds (JVM running for 3.446)
2019-12-12 14:02:59.774 INFO [http-nio-8080-exec-1]o.a.c.c.C.[Tomcat].[localhost].[/foodspringboot].log:173 -Initializing Spring DispatcherServlet 'dispatcherServlet'
2019-12-12 14:02:59.774 INFO [http-nio-8080-exec-1]org.springframework.web.servlet.DispatcherServlet.initServletBean:524 -Initializing Servlet 'dispatcherServlet'
2019-12-12 14:02:59.779 INFO [http-nio-8080-exec-1]org.springframework.web.servlet.DispatcherServlet.initServletBean:546 -Completed initialization in 5 ms
2019-12-12 14:02:59.898 INFO [http-nio-8080-exec-1]io.lettuce.core.EpollProvider.<clinit>:68 -Starting without optional epoll library
2019-12-12 14:02:59.899 INFO [http-nio-8080-exec-1]io.lettuce.core.KqueueProvider.<clinit>:70 -Starting without optional kqueue library
2019-12-12 14:03:38.370 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6300
2019-12-12 14:03:48.385 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6300
2019-12-12 14:03:48.470 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6300
2019-12-12 14:03:58.484 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6300
2019-12-12 14:03:58.570 INFO [lettuce-eventExecutorLoop-1-9]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6300
2019-12-12 14:04:08.591 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6300
2019-12-12 14:04:08.670 INFO [lettuce-eventExecutorLoop-1-11]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6300
2019-12-12 14:04:18.677 WARN [lettuce-nioEventLoop-4-10]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6300
2019-12-12 14:04:18.770 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6300
2019-12-12 14:04:18.795 INFO [lettuce-nioEventLoop-4-12]io.lettuce.core.protocol.ReconnectionHandler.lambda$null$3:177 -Reconnected to 192.168.56.101:6301
2019-12-12 14:20:33.854 WARN [DefaultMessageListenerContainer-1]o.s.jms.listener.DefaultMessageListenerContainer.handleListenerSetupFailure:895 -Setup of JMS message listener invoker failed for destination 'com.foodspringboot.toptic' - trying to recover. Cause: The Consumer is closed
2019-12-12 14:20:33.854 WARN [DefaultMessageListenerContainer-1]o.s.jms.listener.DefaultMessageListenerContainer.handleListenerSetupFailure:895 -Setup of JMS message listener invoker failed for destination 'com.foodspringboot.toptic' - trying to recover. Cause: The Consumer is closed
2019-12-12 14:20:33.856 WARN [DefaultMessageListenerContainer-1]org.messaginghub.pooled.jms.JmsPoolSession.close:115 -Caught exception trying rollback() when putting session back into the pool, will invalidate. javax.jms.IllegalStateException: The Session is closed
javax.jms.IllegalStateException: The Session is closed
	at org.apache.activemq.ActiveMQSession.checkClosed(ActiveMQSession.java:771)
	at org.apache.activemq.ActiveMQSession.rollback(ActiveMQSession.java:596)
	at org.messaginghub.pooled.jms.JmsPoolSession.close(JmsPoolSession.java:112)
	at org.springframework.jms.support.JmsUtils.closeSession(JmsUtils.java:109)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.clearResources(DefaultMessageListenerContainer.java:1241)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1087)
	at java.lang.Thread.run(Thread.java:748)
2019-12-12 14:20:33.856 WARN [DefaultMessageListenerContainer-1]o.s.jms.listener.DefaultMessageListenerContainer.handleListenerSetupFailure:895 -Setup of JMS message listener invoker failed for destination 'com.foodspringboot.queue' - trying to recover. Cause: The Consumer is closed
2019-12-12 14:20:33.969 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6301
2019-12-12 14:20:43.997 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.RedisClient.lambda$connectSentinel$13:596 -Cannot connect Redis Sentinel at RedisURI [host='192.168.56.102', port=26379]: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.102:26379
2019-12-12 14:20:44.001 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.lambda$new$1:111 -Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [RedisURI [host='192.168.56.102', port=26379]], reusing cached address /192.168.56.101:6301
2019-12-12 14:20:44.008 INFO [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ReconnectionHandler.lambda$null$3:177 -Reconnected to /192.168.56.101:6301
2019-12-12 14:23:45.169 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6301
2019-12-12 14:23:55.175 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.RedisClient.lambda$connectSentinel$13:596 -Cannot connect Redis Sentinel at RedisURI [host='192.168.56.102', port=26379]: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.102:26379
2019-12-12 14:23:55.179 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.lambda$new$1:111 -Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [RedisURI [host='192.168.56.102', port=26379]], reusing cached address /192.168.56.101:6301
2019-12-12 14:24:05.184 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 14:24:05.269 INFO [lettuce-eventExecutorLoop-1-9]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6301
2019-12-12 14:24:15.271 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.RedisClient.lambda$connectSentinel$13:596 -Cannot connect Redis Sentinel at RedisURI [host='192.168.56.102', port=26379]: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.102:26379
2019-12-12 14:24:15.272 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.lambda$new$1:111 -Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [RedisURI [host='192.168.56.102', port=26379]], reusing cached address /192.168.56.101:6301
2019-12-12 14:24:25.274 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 14:24:25.370 INFO [lettuce-eventExecutorLoop-1-10]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6301
2019-12-12 14:24:35.375 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.RedisClient.lambda$connectSentinel$13:596 -Cannot connect Redis Sentinel at RedisURI [host='192.168.56.102', port=26379]: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.102:26379
2019-12-12 14:24:35.376 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.lambda$new$1:111 -Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [RedisURI [host='192.168.56.102', port=26379]], reusing cached address /192.168.56.101:6301
2019-12-12 14:24:35.378 INFO [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ReconnectionHandler.lambda$null$3:177 -Reconnected to /192.168.56.101:6301
2019-12-12 14:26:07.870 INFO [lettuce-eventExecutorLoop-1-12]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6301
2019-12-12 14:26:17.872 WARN [lettuce-nioEventLoop-4-9]io.lettuce.core.RedisClient.lambda$connectSentinel$13:596 -Cannot connect Redis Sentinel at RedisURI [host='192.168.56.102', port=26379]: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.102:26379
2019-12-12 14:26:17.874 WARN [lettuce-nioEventLoop-4-9]io.lettuce.core.protocol.ConnectionWatchdog.lambda$new$1:111 -Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [RedisURI [host='192.168.56.102', port=26379]], reusing cached address /192.168.56.101:6301
2019-12-12 14:26:27.876 WARN [lettuce-nioEventLoop-4-10]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 14:26:27.969 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6301
2019-12-12 14:26:37.972 WARN [lettuce-nioEventLoop-4-11]io.lettuce.core.RedisClient.lambda$connectSentinel$13:596 -Cannot connect Redis Sentinel at RedisURI [host='192.168.56.102', port=26379]: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.102:26379
2019-12-12 14:26:37.976 WARN [lettuce-nioEventLoop-4-11]io.lettuce.core.protocol.ConnectionWatchdog.lambda$new$1:111 -Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [RedisURI [host='192.168.56.102', port=26379]], reusing cached address /192.168.56.101:6301
2019-12-12 14:26:47.982 WARN [lettuce-nioEventLoop-4-12]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 14:26:48.069 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6301
2019-12-12 14:26:58.075 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.RedisClient.lambda$connectSentinel$13:596 -Cannot connect Redis Sentinel at RedisURI [host='192.168.56.102', port=26379]: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.102:26379
2019-12-12 14:26:58.079 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.lambda$new$1:111 -Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [RedisURI [host='192.168.56.102', port=26379]], reusing cached address /192.168.56.101:6301
2019-12-12 14:27:08.085 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 14:27:08.169 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6301
2019-12-12 14:27:18.176 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.RedisClient.lambda$connectSentinel$13:596 -Cannot connect Redis Sentinel at RedisURI [host='192.168.56.102', port=26379]: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.102:26379
2019-12-12 14:27:18.179 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.lambda$new$1:111 -Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [RedisURI [host='192.168.56.102', port=26379]], reusing cached address /192.168.56.101:6301
2019-12-12 14:27:28.185 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 14:27:28.270 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6301
2019-12-12 14:27:38.275 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.RedisClient.lambda$connectSentinel$13:596 -Cannot connect Redis Sentinel at RedisURI [host='192.168.56.102', port=26379]: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.102:26379
2019-12-12 14:27:38.278 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.lambda$new$1:111 -Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [RedisURI [host='192.168.56.102', port=26379]], reusing cached address /192.168.56.101:6301
2019-12-12 14:27:48.282 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 14:27:48.369 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6301
2019-12-12 14:27:58.375 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.RedisClient.lambda$connectSentinel$13:596 -Cannot connect Redis Sentinel at RedisURI [host='192.168.56.102', port=26379]: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.102:26379
2019-12-12 14:27:58.378 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.lambda$new$1:111 -Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [RedisURI [host='192.168.56.102', port=26379]], reusing cached address /192.168.56.101:6301
2019-12-12 14:28:08.385 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 14:28:08.468 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6301
2019-12-12 14:28:18.474 WARN [lettuce-nioEventLoop-4-9]io.lettuce.core.RedisClient.lambda$connectSentinel$13:596 -Cannot connect Redis Sentinel at RedisURI [host='192.168.56.102', port=26379]: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.102:26379
2019-12-12 14:28:18.477 WARN [lettuce-nioEventLoop-4-9]io.lettuce.core.protocol.ConnectionWatchdog.lambda$new$1:111 -Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [RedisURI [host='192.168.56.102', port=26379]], reusing cached address /192.168.56.101:6301
2019-12-12 14:28:28.481 WARN [lettuce-nioEventLoop-4-10]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 14:28:28.669 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6301
2019-12-12 14:28:38.674 WARN [lettuce-nioEventLoop-4-11]io.lettuce.core.RedisClient.lambda$connectSentinel$13:596 -Cannot connect Redis Sentinel at RedisURI [host='192.168.56.102', port=26379]: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.102:26379
2019-12-12 14:28:38.676 WARN [lettuce-nioEventLoop-4-11]io.lettuce.core.protocol.ConnectionWatchdog.lambda$new$1:111 -Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [RedisURI [host='192.168.56.102', port=26379]], reusing cached address /192.168.56.101:6301
2019-12-12 14:28:48.680 WARN [lettuce-nioEventLoop-4-12]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 14:28:48.969 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6301
2019-12-12 14:28:58.975 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.RedisClient.lambda$connectSentinel$13:596 -Cannot connect Redis Sentinel at RedisURI [host='192.168.56.102', port=26379]: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.102:26379
2019-12-12 14:28:58.977 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.lambda$new$1:111 -Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [RedisURI [host='192.168.56.102', port=26379]], reusing cached address /192.168.56.101:6301
2019-12-12 14:29:08.982 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 14:29:09.569 INFO [lettuce-eventExecutorLoop-1-9]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6301
2019-12-12 14:29:19.574 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.RedisClient.lambda$connectSentinel$13:596 -Cannot connect Redis Sentinel at RedisURI [host='192.168.56.102', port=26379]: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.102:26379
2019-12-12 14:29:19.576 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.lambda$new$1:111 -Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [RedisURI [host='192.168.56.102', port=26379]], reusing cached address /192.168.56.101:6301
2019-12-12 14:29:29.581 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 14:29:30.669 INFO [lettuce-eventExecutorLoop-1-10]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6301
2019-12-12 14:29:40.677 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.RedisClient.lambda$connectSentinel$13:596 -Cannot connect Redis Sentinel at RedisURI [host='192.168.56.102', port=26379]: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.102:26379
2019-12-12 14:29:40.679 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.lambda$new$1:111 -Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [RedisURI [host='192.168.56.102', port=26379]], reusing cached address /192.168.56.101:6301
2019-12-12 14:29:50.685 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 14:29:52.769 INFO [lettuce-eventExecutorLoop-1-11]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6301
2019-12-12 14:30:02.776 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.RedisClient.lambda$connectSentinel$13:596 -Cannot connect Redis Sentinel at RedisURI [host='192.168.56.102', port=26379]: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.102:26379
2019-12-12 14:30:02.779 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.lambda$new$1:111 -Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [RedisURI [host='192.168.56.102', port=26379]], reusing cached address /192.168.56.101:6301
2019-12-12 14:30:12.783 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 14:30:16.970 INFO [lettuce-eventExecutorLoop-1-12]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6301
2019-12-12 14:30:26.975 WARN [lettuce-nioEventLoop-4-9]io.lettuce.core.RedisClient.lambda$connectSentinel$13:596 -Cannot connect Redis Sentinel at RedisURI [host='192.168.56.102', port=26379]: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.102:26379
2019-12-12 14:30:26.980 WARN [lettuce-nioEventLoop-4-9]io.lettuce.core.protocol.ConnectionWatchdog.lambda$new$1:111 -Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [RedisURI [host='192.168.56.102', port=26379]], reusing cached address /192.168.56.101:6301
2019-12-12 14:30:36.987 WARN [lettuce-nioEventLoop-4-10]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 14:30:45.269 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6301
2019-12-12 14:30:55.276 WARN [lettuce-nioEventLoop-4-11]io.lettuce.core.RedisClient.lambda$connectSentinel$13:596 -Cannot connect Redis Sentinel at RedisURI [host='192.168.56.102', port=26379]: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.102:26379
2019-12-12 14:30:55.279 WARN [lettuce-nioEventLoop-4-11]io.lettuce.core.protocol.ConnectionWatchdog.lambda$new$1:111 -Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [RedisURI [host='192.168.56.102', port=26379]], reusing cached address /192.168.56.101:6301
2019-12-12 14:31:05.284 WARN [lettuce-nioEventLoop-4-12]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 14:31:21.770 INFO [lettuce-eventExecutorLoop-1-2]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6301
2019-12-12 14:31:31.774 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.RedisClient.lambda$connectSentinel$13:596 -Cannot connect Redis Sentinel at RedisURI [host='192.168.56.102', port=26379]: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.102:26379
2019-12-12 14:31:31.776 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.lambda$new$1:111 -Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [RedisURI [host='192.168.56.102', port=26379]], reusing cached address /192.168.56.101:6301
2019-12-12 14:31:41.781 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 14:32:11.868 INFO [lettuce-eventExecutorLoop-1-3]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6301
2019-12-12 14:32:21.873 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.RedisClient.lambda$connectSentinel$13:596 -Cannot connect Redis Sentinel at RedisURI [host='192.168.56.102', port=26379]: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.102:26379
2019-12-12 14:32:21.875 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.lambda$new$1:111 -Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [RedisURI [host='192.168.56.102', port=26379]], reusing cached address /192.168.56.101:6301
2019-12-12 14:32:31.881 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 14:33:01.969 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6301
2019-12-12 14:33:11.974 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.RedisClient.lambda$connectSentinel$13:596 -Cannot connect Redis Sentinel at RedisURI [host='192.168.56.102', port=26379]: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.102:26379
2019-12-12 14:33:11.976 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.lambda$new$1:111 -Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [RedisURI [host='192.168.56.102', port=26379]], reusing cached address /192.168.56.101:6301
2019-12-12 14:33:21.981 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 14:33:52.069 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6301
2019-12-12 14:34:02.074 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.RedisClient.lambda$connectSentinel$13:596 -Cannot connect Redis Sentinel at RedisURI [host='192.168.56.102', port=26379]: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.102:26379
2019-12-12 14:34:02.076 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.lambda$new$1:111 -Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [RedisURI [host='192.168.56.102', port=26379]], reusing cached address /192.168.56.101:6301
2019-12-12 14:34:12.084 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 14:34:42.169 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6301
2019-12-12 14:34:52.174 WARN [lettuce-nioEventLoop-4-9]io.lettuce.core.RedisClient.lambda$connectSentinel$13:596 -Cannot connect Redis Sentinel at RedisURI [host='192.168.56.102', port=26379]: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.102:26379
2019-12-12 14:34:52.176 WARN [lettuce-nioEventLoop-4-9]io.lettuce.core.protocol.ConnectionWatchdog.lambda$new$1:111 -Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [RedisURI [host='192.168.56.102', port=26379]], reusing cached address /192.168.56.101:6301
2019-12-12 14:35:02.180 WARN [lettuce-nioEventLoop-4-10]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 14:35:32.269 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6301
2019-12-12 14:35:42.274 WARN [lettuce-nioEventLoop-4-11]io.lettuce.core.RedisClient.lambda$connectSentinel$13:596 -Cannot connect Redis Sentinel at RedisURI [host='192.168.56.102', port=26379]: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.102:26379
2019-12-12 14:35:42.274 WARN [lettuce-nioEventLoop-4-11]io.lettuce.core.protocol.ConnectionWatchdog.lambda$new$1:111 -Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [RedisURI [host='192.168.56.102', port=26379]], reusing cached address /192.168.56.101:6301
2019-12-12 14:35:52.277 WARN [lettuce-nioEventLoop-4-12]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6301
2019-12-12 15:02:00.961 INFO [restartedMain]com.wl.foodspringboot.FoodSpringBootApplication.logStarting:50 -Starting FoodSpringBootApplication on DESKTOP-814O8JJ with PID 1224 (E:\Learn\IdeaProjects\FoodSpringBoot\target\classes started by WL in E:\Learn\IdeaProjects\FoodSpringBoot)
2019-12-12 15:02:00.963 INFO [restartedMain]com.wl.foodspringboot.FoodSpringBootApplication.logStartupProfileInfo:647 -No active profile set, falling back to default profiles: default
2019-12-12 15:02:00.996 INFO [restartedMain]o.s.b.devtools.env.DevToolsPropertyDefaultsPostProcessor.logTo:225 -Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
2019-12-12 15:02:00.996 INFO [restartedMain]o.s.b.devtools.env.DevToolsPropertyDefaultsPostProcessor.logTo:225 -For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
2019-12-12 15:02:01.522 INFO [restartedMain]o.s.d.repository.config.RepositoryConfigurationDelegate.multipleStoresDetected:244 -Multiple Spring Data modules found, entering strict repository configuration mode!
2019-12-12 15:02:01.524 INFO [restartedMain]o.s.d.repository.config.RepositoryConfigurationDelegate.registerRepositoriesIn:126 -Bootstrapping Spring Data repositories in DEFAULT mode.
2019-12-12 15:02:01.540 INFO [restartedMain]o.s.d.repository.config.RepositoryConfigurationDelegate.registerRepositoriesIn:182 -Finished Spring Data repository scanning in 7ms. Found 0 repository interfaces.
2019-12-12 15:02:01.786 INFO [restartedMain]o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.postProcessAfterInitialization:330 -Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$8487787c] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-12-12 15:02:02.002 INFO [restartedMain]o.s.boot.web.embedded.tomcat.TomcatWebServer.initialize:90 -Tomcat initialized with port(s): 8080 (http)
2019-12-12 15:02:02.012 INFO [restartedMain]org.apache.coyote.http11.Http11NioProtocol.log:173 -Initializing ProtocolHandler ["http-nio-8080"]
2019-12-12 15:02:02.021 INFO [restartedMain]org.apache.catalina.core.StandardService.log:173 -Starting service [Tomcat]
2019-12-12 15:02:02.024 INFO [restartedMain]org.apache.catalina.core.StandardEngine.log:173 -Starting Servlet engine: [Apache Tomcat/9.0.22]
2019-12-12 15:02:02.028 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -An older version [1.2.21] of the APR based Apache Tomcat Native library is installed, while Tomcat recommends a minimum version of [1.2.23]
2019-12-12 15:02:02.028 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -Loaded APR based Apache Tomcat Native library [1.2.21] using APR version [1.6.5].
2019-12-12 15:02:02.028 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
2019-12-12 15:02:02.029 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
2019-12-12 15:02:02.031 INFO [restartedMain]org.apache.catalina.core.AprLifecycleListener.log:173 -OpenSSL successfully initialized [OpenSSL 1.1.1a  20 Nov 2018]
2019-12-12 15:02:02.115 INFO [restartedMain]o.a.c.c.C.[Tomcat].[localhost].[/foodspringboot].log:173 -Initializing Spring embedded WebApplicationContext
2019-12-12 15:02:02.116 INFO [restartedMain]org.springframework.web.context.ContextLoader.prepareWebApplicationContext:284 -Root WebApplicationContext: initialization completed in 1120 ms
2019-12-12 15:02:02.379 INFO [restartedMain]org.messaginghub.pooled.jms.JmsPoolConnectionFactory.setConnectionFactory:198 -Provided ConnectionFactory implementation is JMS 2.0+ capable.
2019-12-12 15:02:02.698 INFO [restartedMain]o.s.scheduling.concurrent.ThreadPoolTaskExecutor.initialize:171 -Initializing ExecutorService 'applicationTaskExecutor'
2019-12-12 15:02:02.740 INFO [restartedMain]o.s.b.a.web.servlet.WelcomePageHandlerMapping.<init>:54 -Adding welcome page: class path resource [public/index.html]
2019-12-12 15:02:02.769 WARN [restartedMain]org.thymeleaf.templatemode.TemplateMode.parse:150 -[THYMELEAF][restartedMain] Template Mode 'HTML5' is deprecated. Using Template Mode 'HTML' instead.
2019-12-12 15:02:02.926 INFO [restartedMain]o.s.boot.devtools.autoconfigure.OptionalLiveReloadServer.startServer:57 -LiveReload server is running on port 35729
2019-12-12 15:02:03.184 INFO [restartedMain]org.apache.coyote.http11.Http11NioProtocol.log:173 -Starting ProtocolHandler ["http-nio-8080"]
2019-12-12 15:02:03.200 INFO [restartedMain]o.s.boot.web.embedded.tomcat.TomcatWebServer.start:202 -Tomcat started on port(s): 8080 (http) with context path '/foodspringboot'
2019-12-12 15:02:03.202 INFO [restartedMain]com.wl.foodspringboot.FoodSpringBootApplication.logStarted:59 -Started FoodSpringBootApplication in 2.526 seconds (JVM running for 3.463)
2019-12-12 15:02:07.947 INFO [http-nio-8080-exec-1]o.a.c.c.C.[Tomcat].[localhost].[/foodspringboot].log:173 -Initializing Spring DispatcherServlet 'dispatcherServlet'
2019-12-12 15:02:07.947 INFO [http-nio-8080-exec-1]org.springframework.web.servlet.DispatcherServlet.initServletBean:524 -Initializing Servlet 'dispatcherServlet'
2019-12-12 15:02:07.952 INFO [http-nio-8080-exec-1]org.springframework.web.servlet.DispatcherServlet.initServletBean:546 -Completed initialization in 5 ms
2019-12-12 15:02:08.070 INFO [http-nio-8080-exec-1]io.lettuce.core.EpollProvider.<clinit>:68 -Starting without optional epoll library
2019-12-12 15:02:08.071 INFO [http-nio-8080-exec-1]io.lettuce.core.KqueueProvider.<clinit>:70 -Starting without optional kqueue library
2019-12-12 15:04:02.916 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6300
2019-12-12 15:04:12.931 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6300
2019-12-12 15:04:13.016 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6300
2019-12-12 15:04:23.040 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6300
2019-12-12 15:04:23.116 INFO [lettuce-eventExecutorLoop-1-9]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6300
2019-12-12 15:04:33.123 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6300
2019-12-12 15:04:33.217 INFO [lettuce-eventExecutorLoop-1-11]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6300
2019-12-12 15:04:43.240 WARN [lettuce-nioEventLoop-4-10]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6300
2019-12-12 15:04:43.315 INFO [lettuce-eventExecutorLoop-1-1]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was 192.168.56.101:6300
2019-12-12 15:04:43.328 INFO [lettuce-nioEventLoop-4-12]io.lettuce.core.protocol.ReconnectionHandler.lambda$null$3:177 -Reconnected to 192.168.56.101:6302
2019-12-12 15:40:46.573 WARN [DefaultMessageListenerContainer-1]o.s.jms.listener.DefaultMessageListenerContainer.handleListenerSetupFailure:895 -Setup of JMS message listener invoker failed for destination 'com.foodspringboot.toptic' - trying to recover. Cause: The Consumer is closed
2019-12-12 15:40:46.573 WARN [DefaultMessageListenerContainer-1]o.s.jms.listener.DefaultMessageListenerContainer.handleListenerSetupFailure:895 -Setup of JMS message listener invoker failed for destination 'com.foodspringboot.toptic' - trying to recover. Cause: The Consumer is closed
2019-12-12 15:40:46.574 WARN [DefaultMessageListenerContainer-1]org.messaginghub.pooled.jms.JmsPoolSession.close:115 -Caught exception trying rollback() when putting session back into the pool, will invalidate. javax.jms.IllegalStateException: The Session is closed
javax.jms.IllegalStateException: The Session is closed
	at org.apache.activemq.ActiveMQSession.checkClosed(ActiveMQSession.java:771)
	at org.apache.activemq.ActiveMQSession.rollback(ActiveMQSession.java:596)
	at org.messaginghub.pooled.jms.JmsPoolSession.close(JmsPoolSession.java:112)
	at org.springframework.jms.support.JmsUtils.closeSession(JmsUtils.java:109)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.clearResources(DefaultMessageListenerContainer.java:1241)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1087)
	at java.lang.Thread.run(Thread.java:748)
2019-12-12 15:40:46.575 WARN [DefaultMessageListenerContainer-1]o.s.jms.listener.DefaultMessageListenerContainer.handleListenerSetupFailure:895 -Setup of JMS message listener invoker failed for destination 'com.foodspringboot.queue' - trying to recover. Cause: The Consumer is closed
2019-12-12 15:40:46.716 INFO [lettuce-eventExecutorLoop-1-4]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6302
2019-12-12 15:40:56.730 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.RedisClient.lambda$connectSentinel$13:596 -Cannot connect Redis Sentinel at RedisURI [host='192.168.56.102', port=26379]: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.102:26379
2019-12-12 15:40:56.733 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.lambda$new$1:111 -Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [RedisURI [host='192.168.56.102', port=26379]], reusing cached address /192.168.56.101:6302
2019-12-12 15:41:06.740 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6302
2019-12-12 15:41:06.816 INFO [lettuce-eventExecutorLoop-1-5]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6302
2019-12-12 15:41:16.823 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.RedisClient.lambda$connectSentinel$13:596 -Cannot connect Redis Sentinel at RedisURI [host='192.168.56.102', port=26379]: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.102:26379
2019-12-12 15:41:16.827 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.lambda$new$1:111 -Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [RedisURI [host='192.168.56.102', port=26379]], reusing cached address /192.168.56.101:6302
2019-12-12 15:41:26.835 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6302
2019-12-12 15:41:26.916 INFO [lettuce-eventExecutorLoop-1-6]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6302
2019-12-12 15:41:36.921 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.RedisClient.lambda$connectSentinel$13:596 -Cannot connect Redis Sentinel at RedisURI [host='192.168.56.102', port=26379]: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.102:26379
2019-12-12 15:41:36.925 WARN [lettuce-nioEventLoop-4-5]io.lettuce.core.protocol.ConnectionWatchdog.lambda$new$1:111 -Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [RedisURI [host='192.168.56.102', port=26379]], reusing cached address /192.168.56.101:6302
2019-12-12 15:41:46.931 WARN [lettuce-nioEventLoop-4-6]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6302
2019-12-12 15:41:47.016 INFO [lettuce-eventExecutorLoop-1-7]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6302
2019-12-12 15:41:57.023 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.RedisClient.lambda$connectSentinel$13:596 -Cannot connect Redis Sentinel at RedisURI [host='192.168.56.102', port=26379]: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.102:26379
2019-12-12 15:41:57.027 WARN [lettuce-nioEventLoop-4-7]io.lettuce.core.protocol.ConnectionWatchdog.lambda$new$1:111 -Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [RedisURI [host='192.168.56.102', port=26379]], reusing cached address /192.168.56.101:6302
2019-12-12 15:42:07.034 WARN [lettuce-nioEventLoop-4-8]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6302
2019-12-12 15:42:07.115 INFO [lettuce-eventExecutorLoop-1-8]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6302
2019-12-12 15:42:17.123 WARN [lettuce-nioEventLoop-4-9]io.lettuce.core.RedisClient.lambda$connectSentinel$13:596 -Cannot connect Redis Sentinel at RedisURI [host='192.168.56.102', port=26379]: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.102:26379
2019-12-12 15:42:17.126 WARN [lettuce-nioEventLoop-4-9]io.lettuce.core.protocol.ConnectionWatchdog.lambda$new$1:111 -Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [RedisURI [host='192.168.56.102', port=26379]], reusing cached address /192.168.56.101:6302
2019-12-12 15:42:27.134 WARN [lettuce-nioEventLoop-4-10]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6302
2019-12-12 15:42:27.216 INFO [lettuce-eventExecutorLoop-1-9]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6302
2019-12-12 15:42:37.223 WARN [lettuce-nioEventLoop-4-11]io.lettuce.core.RedisClient.lambda$connectSentinel$13:596 -Cannot connect Redis Sentinel at RedisURI [host='192.168.56.102', port=26379]: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.102:26379
2019-12-12 15:42:37.227 WARN [lettuce-nioEventLoop-4-11]io.lettuce.core.protocol.ConnectionWatchdog.lambda$new$1:111 -Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [RedisURI [host='192.168.56.102', port=26379]], reusing cached address /192.168.56.101:6302
2019-12-12 15:42:47.233 WARN [lettuce-nioEventLoop-4-12]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6302
2019-12-12 15:42:47.316 INFO [lettuce-eventExecutorLoop-1-10]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6302
2019-12-12 15:42:57.323 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.RedisClient.lambda$connectSentinel$13:596 -Cannot connect Redis Sentinel at RedisURI [host='192.168.56.102', port=26379]: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.102:26379
2019-12-12 15:42:57.327 WARN [lettuce-nioEventLoop-4-1]io.lettuce.core.protocol.ConnectionWatchdog.lambda$new$1:111 -Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [RedisURI [host='192.168.56.102', port=26379]], reusing cached address /192.168.56.101:6302
2019-12-12 15:43:07.334 WARN [lettuce-nioEventLoop-4-2]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6302
2019-12-12 15:43:07.517 INFO [lettuce-eventExecutorLoop-1-11]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6302
2019-12-12 15:43:17.525 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.RedisClient.lambda$connectSentinel$13:596 -Cannot connect Redis Sentinel at RedisURI [host='192.168.56.102', port=26379]: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.102:26379
2019-12-12 15:43:17.528 WARN [lettuce-nioEventLoop-4-3]io.lettuce.core.protocol.ConnectionWatchdog.lambda$new$1:111 -Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [RedisURI [host='192.168.56.102', port=26379]], reusing cached address /192.168.56.101:6302
2019-12-12 15:43:27.534 WARN [lettuce-nioEventLoop-4-4]io.lettuce.core.protocol.ConnectionWatchdog.log:176 -Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.56.101:6302
2019-12-12 15:43:27.815 INFO [lettuce-eventExecutorLoop-1-12]io.lettuce.core.protocol.ConnectionWatchdog.log:173 -Reconnecting, last destination was /192.168.56.101:6302
